### ISSUE TITLE
msthesis

### ISSUE THREAD

**Issue by manujinda** [publicus/unofficial-uoregon-grad-school-dissertation-latex-markdown-apa-format#4]
I am doing a msthesis.

In 0_uothesisapa_preamble \documentclass I changed dissertation to msthesis. If I do not do this, the cover page mentions "A DISSERTATION". For a MS Thesis my belief is that it should be "A Thesis".

Then I got an error. To solve this I had to comment out \committee section in cover.tex. (For Computer Science MS thesis there is no committee. Not sure whether this is universal across all the departments and I have seen even in CIS some MS thesis includes a committee)

It gave another error. To solve this I had to edit the uothesisapa class file.

To fix this, I wrapped lines 394 - 397:

        \if@cochair
          \@cochair& Co-chair\\
        \fi
        \@committee\\ \\ 

like:

      \if@dissertation        % Needs to compile a msthesis
        \if@cochair
          \@cochair& Co-chair\\
        \fi
        \@committee\\ \\ 
      \fi                     % Needs to compile a msthesis

This made everything compile without errors.

I used pdflated main.tex to compile everything.

I did not commit any changes (don't know whether I can).
Thanks for managing this repo. It is very helpful.

**Comment by jglev** [comment]
Hello,

Thank you for your comment! You're always welcome to submit a Pull Request.

As of commit 60164928 this morning, I've added a `lackscommittee` option that you can set to stop rendering of the Committee. The current UO style guide does show a Committee for at least some theses (see p. 43 of [this pdf](https://gradschool.uoregon.edu/sites/gradschool2.uoregon.edu/files/ETD_Style_Manual_2015-2016final032016.pdf "UO Thesis and Dissertation Style Guide"), which is why I haven't implemented your `\if@dissertation` solution but instead took this other approach.

I've also added documentation in [this section](https://github.com/publicus/unofficial-uoregon-grad-school-dissertation-latex-markdown-apa-format#rendering-draft-vs-final-versions-of-your-dissertation "Readme") of the Readme. In that section, I've also added a note that `msthesis` can be declared as the `documentclass` instead of `dissertation`.

Do this new option and documentation work for you and address the issues you raised here? Let me know; if so, I'll close this issue.

My very best,
Jacob

**Comment by manujinda** [comment]
When I tried lackscommittee option, I got the error.

! LaTeX Error: Unknown option `lackscommittee' for package `apacite'.

**Comment by jglev** [comment]
I just confirmed with a fresh clone of the github repo. that the option works on my system. Thus, would you be willing to confirm the following:

1. Are you using the most up-to-date version of the repo.?
1. Assuming you're running the most current version of the repo., does running `./testing_script/Run_Tests_to_Make_Sure_that_Everything_Builds.sh` work without errors?

My very best,
Jacob

**Comment by manujinda** [comment]
Yes. It worked with the current repo. Thank you.
